### ISSUE TITLE
Fireplace project

### ISSUE THREAD

**Issue by technicalpickles** [technicalpickles/picklehome#16]
Our house has a fireplace. It has a gas log which should be replaced, and it's not even hooked up to gas. We put up a child proofing gate around it, just in case, which seems riduculous because there's not even anything in there.

BUT THERE COULD BE

I was thinking to put an unused TV in there, and do some automation. "Alexa, turn on fireplace", to start playing something like [this fireplace](https://www.youtube.com/watch?v=eyU3bRy2x44&t=113s). Could also be added to my [christmas cheer automation](https://github.com/technicalpickles/picklehome-homeassistant-config/blob/master/scripts/christmas_cheer_on.yaml).

I have a spare raspberry pi, so just need something to run on it. [kodi](https://kodi.tv/) has [homeassistant support](https://home-assistant.io/components/media_player.kodi/), and there's [a few options](http://kodi.wiki/view/HOW-TO:Install_Kodi_on_Raspberry_Pi)

I started collecting some notes about [kodi in the wiki](https://github.com/technicalpickles/picklehome/wiki/Kodi). There's a [youtube addon](http://kodi.wiki/view/Add-on:YouTube). I found [this example](https://community.home-assistant.io/t/youtube-songs-play-with-kodi/2234) to play stuff on the kodi:

```
service: media_player.play_media
data:
  entity_id: media_player.kodi
  media_content_id: "plugin://plugin.video.youtube/?path=/root/video&action=play_video&videoid=Xud-J6IQmLI"
  media_content_type: "video"
```
